"""add sync review fields

Revision ID: 1b117abdc7f0
Revises: c71bca4337ab
Create Date: 2026-09-18 14:14:58.805251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b117abdc7f0'
down_revision: Union[str, Sequence[str], None] = 'c71bca4337ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('external_account_id', sa.String(length=200), nullable=False))
    op.create_unique_constraint('uq_linked_accounts_consent_external_account', 'linked_accounts', ['consent_id', 'external_account_id'])
    op.add_column('transactions', sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_transactions_user_needs_review', 'transactions', ['user_id'], unique=False, postgresql_where=sa.text('needs_review = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_needs_review', table_name='transactions', postgresql_where=sa.text('needs_review = true'))
    op.drop_column('transactions', 'needs_review')
    op.drop_constraint('uq_linked_accounts_consent_external_account', 'linked_accounts', type_='unique')
    op.drop_column('linked_accounts', 'external_account_id')
    # ### end Alembic commands ###
