"""add ai categorization enabled setting

Revision ID: 43b64866b554
Revises: bf0fbd916161
Create Date: 2026-09-24 07:52:22.051210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b64866b554'
down_revision: Union[str, Sequence[str], None] = 'bf0fbd916161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('ai_categorization_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ai_categorization_enabled')
    # ### end Alembic commands ###
