"""add unique index for active category names per user

Revision ID: 540ba876a3c6
Revises: c2c554e0641a
Create Date: 2026-09-17 23:01:03.833748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ba876a3c6'
down_revision: Union[str, Sequence[str], None] = 'c2c554e0641a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_categories_user_name_active', 'categories', ['user_id', 'name'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL AND is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_user_name_active', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL AND is_active = true'))
    # ### end Alembic commands ###
