"""create receipts

Revision ID: 83ee0ba75312
Revises: 7ba459b17a4e
Create Date: 2026-09-15 23:14:37.299727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ee0ba75312'
down_revision: Union[str, Sequence[str], None] = '7ba459b17a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'confirmed', 'failed', name='receipt_status', native_enum=False, length=20), nullable=False),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_error', sa.String(length=500), nullable=True),
    sa.Column('extracted_merchant', sa.String(length=200), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('extracted_tax_minor', sa.BigInteger(), nullable=True),
    sa.Column('extracted_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_merchant', sa.String(length=200), nullable=True),
    sa.Column('confirmed_date', sa.Date(), nullable=True),
    sa.Column('confirmed_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_tax_minor', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_receipts_transaction_id'), 'receipts', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_transaction_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
