"""create recurring transactions

Revision ID: 8b4c4d101fb8
Revises: 3ec63d03190b
Create Date: 2026-09-15 11:16:09.863033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4c4d101fb8'
down_revision: Union[str, Sequence[str], None] = '3ec63d03190b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='recurring_transaction_type', native_enum=False, length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'yearly', name='recurrence_frequency', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('income', 'expense')", name='ck_recurring_transactions_type_not_transfer'),
    sa.CheckConstraint('amount_minor > 0', name='ck_recurring_transactions_amount_positive'),
    sa.CheckConstraint('day_of_month >= 1 AND day_of_month <= 31', name='ck_recurring_transactions_day_of_month'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_account_id'), 'recurring_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_category_id'), 'recurring_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('recurring_transaction_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_recurring_transaction_id'), 'transactions', ['recurring_transaction_id'], unique=False)
    op.create_unique_constraint('uq_transactions_recurring_occurrence', 'transactions', ['recurring_transaction_id', 'occurred_at'])
    op.create_foreign_key(
        'transactions_recurring_transaction_id_fkey',
        'transactions', 'recurring_transactions', ['recurring_transaction_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'transactions_recurring_transaction_id_fkey', 'transactions', type_='foreignkey'
    )
    op.drop_constraint('uq_transactions_recurring_occurrence', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_recurring_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'recurring_transaction_id')
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_category_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_account_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
