"""create merchant category rules

Revision ID: bf0fbd916161
Revises: 1b117abdc7f0
Create Date: 2026-09-18 16:14:27.403635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0fbd916161'
down_revision: Union[str, Sequence[str], None] = '1b117abdc7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_category_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_key', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_merchant_category_rules_user_merchant')
    )
    op.create_index(op.f('ix_merchant_category_rules_category_id'), 'merchant_category_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_merchant_category_rules_user_id'), 'merchant_category_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_category_rules_user_id'), table_name='merchant_category_rules')
    op.drop_index(op.f('ix_merchant_category_rules_category_id'), table_name='merchant_category_rules')
    op.drop_table('merchant_category_rules')
    # ### end Alembic commands ###
