"""create linked accounts and sync runs

Revision ID: c71bca4337ab
Revises: 540ba876a3c6
Create Date: 2026-09-18 10:47:37.822130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71bca4337ab'
down_revision: Union[str, Sequence[str], None] = '540ba876a3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_institution_name', sa.String(length=200), nullable=False),
    sa.Column('fip_reference', sa.String(length=200), nullable=True),
    sa.Column('consent_id', sa.String(length=200), nullable=False),
    sa.Column('consent_status', sa.Enum('pending', 'active', 'paused', 'revoked', 'expired', name='sync_consent_status', native_enum=False, length=20), nullable=False),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('masked_account_ref', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_accounts_account_id'), 'linked_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_linked_accounts_user_id'), 'linked_accounts', ['user_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('linked_account_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'partial', 'failed', name='sync_run_status', native_enum=False, length=20), nullable=False),
    sa.Column('transactions_fetched', sa.Integer(), nullable=False),
    sa.Column('transactions_created', sa.Integer(), nullable=False),
    sa.Column('transactions_skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['linked_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_linked_account_id'), 'sync_runs', ['linked_account_id'], unique=False)
    op.add_column('transactions', sa.Column('linked_account_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('external_transaction_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_transactions_linked_account_id'), 'transactions', ['linked_account_id'], unique=False)
    op.create_index('uq_transactions_linked_account_external_id', 'transactions', ['linked_account_id', 'external_transaction_id'], unique=True, postgresql_where=sa.text('linked_account_id IS NOT NULL'))
    op.create_foreign_key(
        'transactions_linked_account_id_fkey',
        'transactions', 'linked_accounts', ['linked_account_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_linked_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_index('uq_transactions_linked_account_external_id', table_name='transactions', postgresql_where=sa.text('linked_account_id IS NOT NULL'))
    op.drop_index(op.f('ix_transactions_linked_account_id'), table_name='transactions')
    op.drop_column('transactions', 'external_transaction_id')
    op.drop_column('transactions', 'linked_account_id')
    op.drop_index(op.f('ix_sync_runs_linked_account_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_linked_accounts_user_id'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_account_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    # ### end Alembic commands ###
