"""create accounts, credit_card_details, categories

Revision ID: fe9868ef4632
Revises: 9621dd83d616
Create Date: 2026-09-14 18:47:44.625928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9868ef4632'
down_revision: Union[str, Sequence[str], None] = '9621dd83d616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed ids (not gen_random_uuid()) so downgrade() can remove exactly these
# seeded rows, and so re-running against a fresh database is deterministic.
DEFAULT_CATEGORIES = [
    {"id": "00000000-0000-0000-0000-000000000001", "name": "Food", "icon": "🍔", "color": "#F97316"},
    {"id": "00000000-0000-0000-0000-000000000002", "name": "Transport", "icon": "🚗", "color": "#3B82F6"},
    {"id": "00000000-0000-0000-0000-000000000003", "name": "Shopping", "icon": "🛍️", "color": "#EC4899"},
    {"id": "00000000-0000-0000-0000-000000000004", "name": "Bills", "icon": "🧾", "color": "#6366F1"},
    {"id": "00000000-0000-0000-0000-000000000005", "name": "Entertainment", "icon": "🎬", "color": "#A855F7"},
    {"id": "00000000-0000-0000-0000-000000000006", "name": "Education", "icon": "🎓", "color": "#14B8A6"},
    {"id": "00000000-0000-0000-0000-000000000007", "name": "Health", "icon": "⚕️", "color": "#EF4444"},
    {"id": "00000000-0000-0000-0000-000000000008", "name": "Travel", "icon": "✈️", "color": "#0EA5E9"},
    {"id": "00000000-0000-0000-0000-000000000009", "name": "Subscriptions", "icon": "🔁", "color": "#8B5CF6"},
    {"id": "00000000-0000-0000-0000-000000000010", "name": "Rent", "icon": "🏠", "color": "#F59E0B"},
    {"id": "00000000-0000-0000-0000-000000000011", "name": "Utilities", "icon": "💡", "color": "#EAB308"},
    {"id": "00000000-0000-0000-0000-000000000012", "name": "Insurance", "icon": "🛡️", "color": "#10B981"},
    {"id": "00000000-0000-0000-0000-000000000013", "name": "Investment", "icon": "📈", "color": "#22C55E"},
    {"id": "00000000-0000-0000-0000-000000000014", "name": "Other", "icon": "📦", "color": "#6B7280"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('BANK_ACCOUNT', 'CASH', 'CREDIT_CARD', 'UPI', 'SAVINGS_ACCOUNT', 'WALLET', name='account_type', native_enum=False, length=20), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('budget_minor', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('credit_card_details',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('credit_limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('statement_day', sa.SmallInteger(), nullable=False),
    sa.Column('payment_due_day', sa.SmallInteger(), nullable=False),
    sa.Column('minimum_payment_minor', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_details_account_id'), 'credit_card_details', ['account_id'], unique=True)
    # ### end Alembic commands ###

    categories_table = sa.table(
        'categories',
        sa.column('id', sa.UUID()),
        sa.column('user_id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('icon', sa.String()),
        sa.column('color', sa.String()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "id": c["id"],
                "user_id": None,
                "name": c["name"],
                "icon": c["icon"],
                "color": c["color"],
                "is_active": True,
            }
            for c in DEFAULT_CATEGORIES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Dropping the categories table below removes the seeded default rows too -
    # no separate DELETE of DEFAULT_CATEGORIES is needed.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_card_details_account_id'), table_name='credit_card_details')
    op.drop_table('credit_card_details')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
